### ISSUE TITLE
Fehler in Lamda 4.9

### ISSUE THREAD

**Issue by mnbvghw** [wipplingermax/2022-SoSe-ITH#3]
Statt dem Sigma Symbol steht: "MCPCSigma" Und P/C wurde vertauscht: MPCP heißt es.

**Comment by mnbvghw** [comment]
Weiter unten steht: (σl ef tarrow(u1 ), ∗σr ightarrow(v1 ))

**Comment by wipplingermax** [comment]
Fixed in 29f1fda1607cc9f5ded21872f27a20d26219de35

Danke. Gerne nächstes Mal auch Seitenzahl angeben.
